In [2]:
import numpy as np 
import pandas as pd

In [3]:
customers={"Customerıd":[1,2,3,4],
           "Customer Name":["yalçındağ","mustafa","ede turzim","kiya inşaat"],
           "Customer City":["istanbul","istanbul","ankara","ankara"],
           "age":[np.nan,23,np.nan,56]}

In [4]:
customerDF= pd.DataFrame(customers,columns=["Customerıd","Customer Name","Customer City","age"])
customerDF

   Customerıd Customer Name Customer City   age
0           1     yalçındağ      istanbul   NaN
1           2       mustafa      istanbul  23.0
2           3    ede turzim        ankara   NaN
3           4   kiya inşaat        ankara  56.0

In [5]:
sales={"Saleıd":[23,52,41,36],
       "Customerıd":[1,2,3,4],
       "Product":["çimento","bilet","bilet","çimento"],
       "Amounnt":[541,750,123,np.nan]}
saleDF=pd.DataFrame(sales)
saleDF

   Saleıd  Customerıd  Product  Amounnt
0      23           1  çimento    541.0
1      52           2    bilet    750.0
2      41           3    bilet    123.0
3      36           4  çimento      NaN

In [6]:
regionsDF=pd.DataFrame({"City":["urfa","urfa","amarika","amerika"],"Region":["doğu","doğu","kuzey","kuzey"]},columns=["City","Region"])
regionsDF

      City Region
0     urfa   doğu
1     urfa   doğu
2  amarika  kuzey
3  amerika  kuzey

In [7]:
customerDF.isnull() # eksik veri var mı sorusunu sorar

   Customerıd  Customer Name  Customer City    age
0       False          False          False   True
1       False          False          False  False
2       False          False          False   True
3       False          False          False  False

In [8]:
saleDF.isnull() # eksik veri var mı sorusunu sorar # true olanlar eksik veridir

   Saleıd  Customerıd  Product  Amounnt
0   False       False    False    False
1   False       False    False    False
2   False       False    False    False
3   False       False    False     True

In [9]:
customerDF

   Customerıd Customer Name Customer City   age
0           1     yalçındağ      istanbul   NaN
1           2       mustafa      istanbul  23.0
2           3    ede turzim        ankara   NaN
3           4   kiya inşaat        ankara  56.0

In [10]:
customeryasort=customerDF["age"].mean() # var olan yaş verilerinin ortalamasını aldık

In [11]:
customerDF["age"].fillna(customeryasort) # var olan yaş verilerinin ortalaması ile eksik  yaş olan verileri doldurduk
customerDF

   Customerıd Customer Name Customer City   age
0           1     yalçındağ      istanbul   NaN
1           2       mustafa      istanbul  23.0
2           3    ede turzim        ankara   NaN
3           4   kiya inşaat        ankara  56.0

In [12]:
saleDF

   Saleıd  Customerıd  Product  Amounnt
0      23           1  çimento    541.0
1      52           2    bilet    750.0
2      41           3    bilet    123.0
3      36           4  çimento      NaN

In [13]:
saleDF.dropna(inplace=True) # satış tutarı eksik olan kayıtlrı sildik ve kaydettik
saleDF

   Saleıd  Customerıd  Product  Amounnt
0      23           1  çimento    541.0
1      52           2    bilet    750.0
2      41           3    bilet    123.0

In [14]:
birlesmisDF=pd.merge(customerDF,saleDF,on=("Customerıd"))
birlesmisDF   # merge ile ortak columnsdan iki dataframei birleştirdik

   Customerıd Customer Name Customer City   age  Saleıd  Product  Amounnt
0           1     yalçındağ      istanbul   NaN      23  çimento    541.0
1           2       mustafa      istanbul  23.0      52    bilet    750.0
2           3    ede turzim        ankara   NaN      41    bilet    123.0

In [15]:
yenibirlesmisDF=pd.concat([regionsDF,birlesmisDF],axis=1) # bu şekilde regons tablosunudan sütunu şeklinde eklemiş olduk
yenibirlesmisDF

,City,Region,Customerıd,Customer Name,Customer City,age,Saleıd,Product,Amounnt
0,urfa,doğu,1.0,yalçındağ,istanbul,NaN,23.0,çimento,541.0
1,urfa,doğu,2.0,mustafa,istanbul,23.0,52.0,bilet,750.0
2,amarika,kuzey,3.0,ede turzim,ankara,NaN,41.0,bilet,123.0
3,amerika,kuzey,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
sehirler=yenibirlesmisDF.groupby("City")
sehirler.sum("Amount") # bize şehir bazlı toplam satışı getirdi

         Customerıd   age  Saleıd  Amounnt
City
amarika         3.0   0.0    41.0    123.0
amerika         0.0   0.0     0.0      0.0
urfa            3.0  23.0    75.0   1291.0

In [17]:
bolge=yenibirlesmisDF.groupby("Region")
bolge.sum("amount") # bölge bazlı toplam harcamyı getirdi

        Customerıd   age  Saleıd  Amounnt
Region
doğu           3.0  23.0    75.0   1291.0
kuzey          3.0   0.0    41.0    123.0

In [18]:
urun=yenibirlesmisDF.groupby("Product")
urun.mean("amaout") # ürün bazlı ortalamyı gösterdi

         Customerıd   age  Saleıd  Amounnt
Product
bilet           2.5  23.0    46.5    436.5
çimento         1.0   NaN    23.0    541.0

In [19]:
yenibirlesmisDF

,City,Region,Customerıd,Customer Name,Customer City,age,Saleıd,Product,Amounnt
0,urfa,doğu,1.0,yalçındağ,istanbul,NaN,23.0,çimento,541.0
1,urfa,doğu,2.0,mustafa,istanbul,23.0,52.0,bilet,750.0
2,amarika,kuzey,3.0,ede turzim,ankara,NaN,41.0,bilet,123.0
3,amerika,kuzey,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
salesMart = pd.DataFrame({
    "SaleID": [1,5,7,8],
    "CustomerID": [99,104,206,207],
    "Product": ["Laptop","Tablet","Telefon","Saç maşası"],
    "Amount": [45000, 12860, 37000, 3100],
    "Month": ["2026-03", "2026-03", "2026-03", "2026-03"]
})

salesEyl = pd.DataFrame({
    "SaleID": [2,6,7],
    "CustomerID": [100,105,207],
    "Product": ["Kulaklık","Laptop","Saç maşası"],
    "Amount": [2300,72950, 3100],
    "Month": ["2026-09", "2026-09", "2026-09"]
    
})

In [21]:
aybirleştirme=pd.concat([salesMart,salesEyl], ignore_index=True) 
aybirleştirme                                 # yukarıdaki indexi sıfırlar

   SaleID  CustomerID     Product  Amount    Month
0       1          99      Laptop   45000  2026-03
1       5         104      Tablet   12860  2026-03
2       7         206     Telefon   37000  2026-03
3       8         207  Saç maşası    3100  2026-03
4       2         100    Kulaklık    2300  2026-09
5       6         105      Laptop   72950  2026-09
6       7         207  Saç maşası    3100  2026-09

In [22]:
aybirleştirme["KDV"] = aybirleştirme["Amount"] * 1.20
print("KDV eklenmiş satış tutarı: ")
aybirleştirme

#apply() kullanımı -> Satış tutarına göre kategori oluşturalım
def satisKategori(amount):
    if amount >= 40000:
        return "Premium"
    elif amount >= 25000:
        return "Gold"
    elif amount >= 10000:
        return "Standard"
    else:
        return "Basic"
aybirleştirme["Category"] = aybirleştirme["Amount"].apply(satisKategori)
print("Kateogri eklenmiş hali: ")
aybirleştirme

KDV eklenmiş satış tutarı:
Kateogri eklenmiş hali:

   SaleID  CustomerID     Product  Amount    Month      KDV  Category
0       1          99      Laptop   45000  2026-03  54000.0   Premium
1       5         104      Tablet   12860  2026-03  15432.0  Standard
2       7         206     Telefon   37000  2026-03  44400.0      Gold
3       8         207  Saç maşası    3100  2026-03   3720.0     Basic
4       2         100    Kulaklık    2300  2026-09   2760.0     Basic
5       6         105      Laptop   72950  2026-09  87540.0   Premium
6       7         207  Saç maşası    3100  2026-09   3720.0     Basic

In [23]:
# Temizlenmiş ve analiz edilmiş tabloyu excel'e yaz
aybirleştirme.to_excel("final_sales_report.xlsx", index=False) #dosyayı oluşturdul
print("Excel dosyası yazıldı.")

#Excel dosyasını okuyalım
salesFromExcel = pd.read_excel("final_sales_report.xlsx") #dosyayı tekrar yükledik 
print("Excel'den okunan veri")
display(salesFromExcel)

Excel dosyası yazıldı.
Excel'den okunan veri

   SaleID  CustomerID     Product  Amount    Month    KDV  Category
0       1          99      Laptop   45000  2026-03  54000   Premium
1       5         104      Tablet   12860  2026-03  15432  Standard
2       7         206     Telefon   37000  2026-03  44400      Gold
3       8         207  Saç maşası    3100  2026-03   3720     Basic
4       2         100    Kulaklık    2300  2026-09   2760     Basic
5       6         105      Laptop   72950  2026-09  87540   Premium
6       7         207  Saç maşası    3100  2026-09   3720     Basic

In [24]:
#Toplam satış
toplamsatış= (yenibirlesmisDF["Amounnt"].sum())
print(f"Toplam satış: {toplamsatış}")

#En karlı şehir (en yüksek toplam satış yapan şehir)
enkarlışehır = yenibirlesmisDF.groupby("City")["Amounnt"].sum()
eniyiSehir = enkarlışehır.idxmax()
print(f"En karlı şehir: {eniyiSehir}")

#En güçlü bölge (en yüksek toplam satış yapan bölge)
enguclubolgeismi = yenibirlesmisDF.groupby("Region")["Amounnt"].sum()
enGucluBolge = enguclubolgeismi.idxmax()
print(f"En güçlü bölge: {enGucluBolge}")

Toplam satış: 1414.0
En karlı şehir: urfa
En güçlü bölge: doğu